---
- name: Learning about blocks
  hosts: planetexpress
  connection: ssh   # default connection type
  gather_facts: no

  tasks:

  - name: BLOCK - This is what we want to TRY to do
    block:

      - name: Example task 1
        shell: "echo 'My single task ran' > example.txt"

      - name: Example task 2
        shell: "echo 'My second task ran' >> example.txt"

      - name: Example task 3
        shell: "echo 'My third task ran' >> example.txt"
