---
- name: Apache server installed
  hosts: web
  gather_facts: no
  become: yes

  tasks:

  # the package module tries to select
  # yum or apt or pkg5 (etc) automatically
  - name: remove Apache
    package:
      name: apache2
      state: absent
